CREATE TABLE alumno
(
  id serial NOT NULL primary key,
  nombre character varying,
  apellido character varying,
  mail character varying,
  facebook character varying,
  numerodni character varying,
  tipodni integer references tipo_dni(id),
  calle character varying,
  perfilacademico character varying,
  foto character varying,
  carrera integer references carrera(id),
  ancho character varying,
  alto character varying,
  fechanacimiento character varying,
  numerocalle character varying,
  mail2 character varying,
  twitter character varying,
  provincia_nac character varying,
  localidad_nac character varying,
  provincia_trabajo character varying,
  localidad_trabajo character varying,
  provincia_viviendo character varying,
  localidad_viviendo character varying,
  perfil_laboral character varying,
  password character varying
)